name = "froshwebdav"
main = "worker.js"
workers_dev = false
compatibility_date = "2022-03-04"
account_id = "963ff7fb9c523564b5f3a398ab39d488"
logpush = true
routes = ["webdav.fos.gg/*"]

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "shopStorage"
id = "f2112b386a2b40119f21ce1b4c46e5f8"
preview_id = "f2112b386a2b40119f21ce1b4c46e5f8"
